# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  - board: nice_nano_v2
    shield: sofle_left nice_oled
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: nice_nano_v2
    shield: sofle_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: nice_nano_v2
    shield: sofle_left nice_view_adapter nice_view_gem 
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: nice_nano_v2
    shield: sofle_left nice_view_adapter nice_view 
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y -DCONFIG_ZMK_LV_FONT_DEFAULT_SMALL_MONTSERRAT_26=y -DCONFIG_LV_FONT_DEFAULT_MONTSERRAT_26=y -DCONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
    artifact-name: sofle_left nice_view_adapter nice_view-nice_nano_v2-zmk-olddisplay
  #- board: nice_nano_v2
  #  shield: sofle_right 
  #  #nice_oled
  - board: nice_nano_v2
    shield: sofle_right nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: sofle_right nice_view_adapter nice_view_gem
  - board: nice_nano_v2
    shield: sofle_right nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y -DCONFIG_ZMK_LV_FONT_DEFAULT_SMALL_MONTSERRAT_26=y -DCONFIG_LV_FONT_DEFAULT_MONTSERRAT_26=y -DCONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y 
    artifact-name: sofle_right nice_view_adapter nice_view-nice_nano_v2-zmk-olddisplay
  - board: nice_nano_v2
    shield: settings_reset
