manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects

    # support nice_oled and nice_epaper
    #- name: mctechnology17
    #  url-base: https://github.com/mctechnology17

    # https://github.com/M165437/nice-view-gem
    - name: m165437 #new entry
      url-base: https://github.com/M165437 #new entry  

    # https://github.com/badjeff/zmk-feature-split-esb
    #- name: badjeff
    #  url-base: https://github.com/badjeff
    #- name: nrfconnect
    #  url-base: https://github.com/nrfconnect    

    # zmk-rgbled-widget 
    - name: caksoylar  # <-- new entry
      url-base: https://github.com/caksoylar

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # support nice_oled and nice_epaper
    #- name: zmk-nice-oled
    #  remote: mctechnology17
    #  revision: main

    - name: nice-view-gem #new entry
      remote: m165437 #new entry
      revision: main #new entry

    # ZMK ESB Split Transport
    # https://github.com/badjeff/zmk-feature-split-esb
    #- name: zmk-feature-split-esb
    #  remote: badjeff
    #  revision: main  
    #- name: sdk-nrf
    #  remote: nrfconnect
    #  revision: v2.6.4 # zephyr v3.5.99
    #  path: nrf
    #- name: nrfxlib
    #  remote: nrfconnect
    #  revision: v2.6.4
    #  repo-path: sdk-nrfxlib
    #  path: nrfxlib

    - name: zmk-rgbled-widget  # <-- new entry
      remote: caksoylar
      revision: main
      
  self:
    path: config
