manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects

    # support nice_oled and nice_epaper
    #- name: mctechnology17
    #  url-base: https://github.com/mctechnology17

    # https://github.com/M165437/nice-view-gem
    - name: m165437 #new entry
      url-base: https://github.com/M165437 #new entry  

    # ZMK Feature: Charge Indicator
    # https://github.com/4mplelab/zmk-feature-charge-indicator
    #- name: 4mplelab
    #url-base: https://github.com/4mplelab
      
    # https://github.com/badjeff/zmk-feature-split-esb
    #- name: badjeff
    #  url-base: https://github.com/badjeff
    #- name: nrfconnect
    #  url-base: https://github.com/nrfconnect    

    # zmk-rgbled-widget 
    - name: caksoylar  # <-- new entry
      url-base: https://github.com/caksoylar

    # ZMK Layer Status
    # https://github.com/maatthc/zmk-feature-appcompanion
    # used with Keyboard Layers App Companion
    # https://github.com/maatthc/keyboard_layers_app_companion
    - name: maatthc
      url-base: https://github.com/maatthc

  projects:
    - name: zmk
      remote: zmkfirmware
      #revision: v0.2
      #revision: main
      revision: v0.3
      import: app/west.yml
      
    # support nice_oled and nice_epaper
    #- name: zmk-nice-oled
    #  remote: mctechnology17
    #  revision: main

    - name: nice-view-gem #new entry
      remote: m165437 #new entry
      revision: main #new entry

    # ZMK Feature: Charge Indicator
    #- name: zmk-feature-charge-indicator
    #  remote: 4mplelab
    #  revision: main

    # zmk-feature-scaling is a ZMK input processor that evaluates a configurable acceleration curve 
    # on frame-based pointer input while preserving the resulting direction vector. Trackball?
    # https://github.com/iwk7273/zmk-feature-scaling

    # ZMK Feature: XY Clipper
    # This is a ZMK input processor module to clip relative XY movement deltas from sensors like trackballs or optical sensors.
    # https://github.com/iwk7273/zmk-feature-xy_clipper
    
    # ZMK ESB Split Transport
    # https://github.com/badjeff/zmk-feature-split-esb
    #- name: zmk-feature-split-esb
    #  remote: badjeff
    #  revision: main  
    #- name: sdk-nrf
    #  remote: nrfconnect
    #  revision: v2.6.4 # zephyr v3.5.99
    #  path: nrf
    #- name: nrfxlib
    #  remote: nrfconnect
    #  revision: v2.6.4
    #  repo-path: sdk-nrfxlib
    #  path: nrfxlib

    - name: zmk-rgbled-widget  # <-- new entry
      remote: caksoylar
      revision: main

    # ZMK Layer Status
    # https://github.com/maatthc/zmk-feature-appcompanion
    # used with Keyboard Layers App Companion
    # https://github.com/maatthc/keyboard_layers_app_companion
    - name: zmk-feature-appcompanion
      remote: maatthc
      revision: main

  self:
    path: config
