manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects

    # support nice_oled and nice_epaper
    #- name: mctechnology17
    #  url-base: https://github.com/mctechnology17

    # https://github.com/M165437/nice-view-gem
    - name: m165437 #new entry
      url-base: https://github.com/M165437 #new entry  
      
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # support nice_oled and nice_epaper
    #- name: zmk-nice-oled
    #  remote: mctechnology17
    #  revision: main

    - name: nice-view-gem #new entry
      remote: m165437 #new entry
      revision: main #new entry
      
  self:
    path: config
